"""
routers/analytics.py — All U Cluj analytics endpoints.
Reads from the pre-computed ucluj_analysis.json (generated by aggregate.py).
Fast — no DB needed for these reads.
"""

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

import structlog
from fastapi import APIRouter, HTTPException

log = structlog.get_logger()
router = APIRouter(prefix="/api/v1/ucluj", tags=["analytics"])

ROOT = Path(__file__).resolve().parents[5]
ANALYSIS_FILE = Path("ucluj_analysis.json")

# ── Full-name lookup from raw player metadata ──────────────────────────────

@lru_cache(maxsize=1)
def _load_fullname_map() -> dict[int, str]:
    """Build {wyId -> 'FirstName LastName'} from the raw players metadata file."""
    candidates = [
        ROOT / "Data" / "Date - meciuri" / "players (1).json",
        ROOT / "analytics" / "Data" / "Date - meciuri" / "players (1).json",
        ROOT / "Date-meciuri" / "players (1).json",
    ]
    for path in candidates:
        if path.exists():
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                players = data.get("players", data) if isinstance(data, dict) else data
                return {
                    int(p["wyId"]): f"{p.get('firstName','').strip()} {p.get('lastName','').strip()}".strip()
                    for p in players
                    if p.get("wyId")
                }
            except Exception:
                pass
    return {}


def _enrich_squad(squad: list) -> list:
    """Attach full_name to each squad player using the metadata lookup."""
    fm = _load_fullname_map()
    for p in squad:
        pid = p.get("player_id")
        full = fm.get(pid, "")
        p["full_name"] = full if full else p.get("name", "")
    return squad


def _load() -> dict:
    if not ANALYSIS_FILE.exists():
        raise HTTPException(
            status_code=503,
            detail="Analysis not generated yet. Run: python aggregate.py",
        )
    return json.loads(ANALYSIS_FILE.read_text(encoding="utf-8"))


@router.get("/overview")
def overview() -> dict:
    """Match record + top-line profile scores."""
    data = _load()
    profile = data["team_profile"]
    top_strengths = sorted(profile, key=lambda d: -d["score"])[:3]
    top_weaknesses = sorted(profile, key=lambda d: d["score"])[:3]

    return {
        "generated_at": data["generated_at"],
        "match_record": data["match_record"],
        "squad_size": len(data["squad"]),
        "avg_squad_rating": round(
            sum(p["overall"] for p in data["squad"]) / max(len(data["squad"]), 1), 1
        ),
        "top_strengths": [{"label": d["label"], "score": d["score"]} for d in top_strengths],
        "top_weaknesses": [{"label": d["label"], "score": d["score"]} for d in top_weaknesses],
    }


@router.get("/squad")
def squad() -> list:
    """Full squad with ratings, per-90 stats, verdicts, and full_name."""
    data = _load()
    enriched = _enrich_squad([dict(p) for p in data["squad"]])
    return sorted(enriched, key=lambda p: -p["overall"])


@router.get("/squad/{player_id}")
def player_detail(player_id: int) -> dict:
    data = _load()
    p = next((p for p in data["squad"] if p["player_id"] == player_id), None)
    if not p:
        raise HTTPException(status_code=404, detail=f"Player {player_id} not in U Cluj squad")
    enriched = _enrich_squad([dict(p)])
    return enriched[0]


@router.get("/team-profile")
def team_profile() -> list:
    """12-dimension tactical profile with scores and evidence."""
    return _load()["team_profile"]


@router.get("/team-profile/{dimension_key}")
def profile_dimension(dimension_key: str) -> dict:
    dims = _load()["team_profile"]
    d = next((d for d in dims if d["key"] == dimension_key), None)
    if not d:
        raise HTTPException(status_code=404, detail=f"Dimension '{dimension_key}' not found")
    return d


@router.get("/weaknesses")
def weaknesses() -> dict:
    """
    Where the team struggles most — tactical dimensions with score < 50
    plus players performing below expected for their role.
    """
    data = _load()
    profile = data["team_profile"]
    squad = data["squad"]

    tactical_weak = [d for d in profile if d["score"] < 50]
    tactical_weak.sort(key=lambda d: d["score"])

    underperformers = [
        {
            "name": p["name"], "position": p["position"],
            "overall": p["overall"], "verdict": p["verdict"],
            "weaknesses": p["weaknesses"],
        }
        for p in squad if p["overall"] < 48
    ]
    underperformers.sort(key=lambda p: p["overall"])

    return {
        "tactical_weaknesses": tactical_weak,
        "underperforming_players": underperformers,
        "summary": (
            f"{len(tactical_weak)} dimensiuni tactice slabe. "
            f"{len(underperformers)} jucători sub standard."
        ),
    }


@router.get("/transfer-needs")
def transfer_needs() -> list:
    """Which positions need new players and what profile to look for."""
    return _load()["transfer_needs"]


@router.get("/match-record")
def match_record() -> dict:
    data = _load()
    return data["match_record"]
